### ISSUE TITLE
Problem adding iRule to virtual server

### ISSUE THREAD

**Issue by dsolodow** [joel74/POSH-LTM-Rest#30]
I have a valid F5session variable, and 'Get-F5Status -F5Session $session' returns Active

When I run 'Add-iRuleToVirtualServer -F5Session $f5session -iRuleName '/BIS/Test' -VirtualServer '/BIS/DEV-WebServers.app/DEV-WebServers_vs' -Verbose' it returns:

VERBOSE: NB: Virtual server names are case-specific.
VERBOSE: GET https://f5.contoso.com/mgmt/tm/ltm/virtual/~BIS~DEV-WebServers.app~DEV-WebServers_vs with 0-byte payload
VERBOSE: received 2057-byte response of content type application/json
VERBOSE: NB: iRule names are case-specific.
VERBOSE: GET https://f5.contoso.com/mgmt/tm/ltm/rule/~BIS~Test with 0-byte payload
VERBOSE: received 174-byte response of content type application/json
VERBOSE: PUT https://f5.contoso.com/mgmt/tm/ltm/virtual/~BIS~DEV-WebServers.app~DEV-WebServers_vs?ver=12.0.0 with -1-byte payload
False

**Comment by joel74** [comment]
Hi, Damien,
I did some testing on my end and repro'd the issue. The problem is this: the function expects the partition name to be passed in as a separate parameter, and it expects the iRule and the virtual server to live in the same partition. You could try calling the following and see if it resolves the issue:

`Add-iRuleToVirtualServer -F5Session $f5session -iRuleName 'Test' -VirtualServer 'DEV-WebServers_vs' -Partition 'BIS' -Verbose`

I'm not sure if 'DEV-WebServers.app' will be considered a separate partition under 'BIS,' so lets see what you get.

Thanks,
Joel

**Comment by dsolodow** [comment]
![image](https://cloud.githubusercontent.com/assets/7574074/14442093/e5294a96-0005-11e6-95c6-cd28a75550eb.png)

**Comment by joel74** [comment]
Thanks, Damien. I just committed a change to Add-iRuleToVirtualServer.ps1 to take a VirtualServerPartition param, to differentiate it from the Partition param for the iRule. Please retest when you get a chance and let me know the results. (Unfortunately, I'm working off a single /Common partition in my setup, so my testing with multiple partitions is limited.) Thanks.

**Comment by dsolodow** [comment]
Forward progress, but still an issue:
![image](https://cloud.githubusercontent.com/assets/7574074/14443876/02d9c7a0-0010-11e6-91ca-57f87b161464.png)

**Comment by joel74** [comment]
Looks like it's not using the passed in partition for the irule. I'll check out why in a bit. Thanks.

**Comment by vercellone** [comment]
Please refer to commit bb96238 for the fix.  

If I can clean up the mess I made of my master branch with an unintended merge I'll submit a pull request.  But, you are welcome to extract what you need at your leisure.

**Comment by dsolodow** [comment]
Well, I tried it again with the new commit, and no more error message but the Add-iRuleToVirtualServer still returns False.

Did a Fiddler trace to get some additional info:
Here's the PUT: 
PUT /mgmt/tm/ltm/virtual/~BIS~DEV-WebServers.app~DEV-WebServers_vs?ver=12.0.0 HTTP/1.1

And here's what gets returned:
{"code":400,"message":"0107028c:3: The source (::) and destination (10.100.101.13) addresses for virtual server (/BIS/DEV-WebServers.app/DEV-WebServers_vs) must be be the same type (IPv4 or IPv6).","errorStack":[]}

![image](https://cloud.githubusercontent.com/assets/7574074/14462687/34e4c750-0096-11e6-8aaf-8830bdab7fc3.png)

**Comment by vercellone** [comment]
What is the request body for your PUT?  Can you use fiddler to compose a PUT request that does work?  It could be a version-specific issue.  I see that your put specifies ?ver=12.0.0.

I successfully added and removed an iRule in the Common partition to a virtual server in our "Production" partition.  The raw PUT request for my add looks like this:

```
PUT https://[LTMName]/mgmt/tm/ltm/virtual/~Production~[app_name]~[VirtualserverName]?ver=11.5.1 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.0.10240.16384
Content-Type: application/json
Authorization: Basic [Base64EncodedAuthValue]
Host: [LTMName]
Content-Length: 81

{
    "rules":  [
                  "/Common/HTTP_Redirect"
              ]
}
```

Reference: https://devcentral.f5.com/questions/examples-of-json-for-adding-an-irule-for-a-virtual-server-via-the-rest-api

**Comment by dsolodow** [comment]
Interesting; the raw put looks essentially the same. I wonder if this is a defect in 12.0; I'll open a case with F5 and see what they say.

**Comment by dsolodow** [comment]
@vercellone , can you try your request but use PATCH instead of PUT?
F5 is telling me that's what I should be using, and sure enough, it works.
Trying to find out if that's a 12.x thing, or if 11.x will work with it as well.

**Comment by vercellone** [comment]
PATCH was successful for both Add and Remove.  I wonder if we should do the same for *-Pool(Member|Monitor)*.
